#- name: Set Prompt
#  ansible.builtin.shell: set-prompt grafana
#
#- name: Copy grafana repo file
#  ansible.builtin.template:
#    src: grafana.repo
#    dest: /etc/yum.repos.d/grafana.repo
#
#- name: Install Grafana
#  ansible.builtin.dnf:
#    name: grafana
#    state: installed

- name: Copy Datasource
  ansible.builtin.template:
    src: prom-datasource.yml
    dest: /etc/grafana/provisioning/datasources/prom.yml

- name: Copy template
  ansible.builtin.template:
    src: sample-dash.json
    dest: /tmp/sample-dash.json

- name: Create a folder
  community.grafana.grafana_folder:
    url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: "psrikanth@123"
    title: "ProjectDashboards"
    state: present

- name: Import Grafana dashboards folder
  community.grafana.grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: "admin"
    grafana_password: "admin123"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/sample-dash.json
    folder: ProjectDashboards

- name: Start Grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    enabled: yes

