- name: Set Prompt
  ansible.builtin.shell: set-prompt ci-server

- name: Create runner directory
  ansible.builtin.file:
    path: /home/ec2-user/github-runner
    state: directory
  become_user: ec2-user

- name: Download Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.315.0/actions-runner-linux-x64-2.315.0.tar.gz
    dest: /home/ec2-user/github-runner
    remote_src: yes
  become_user: ec2-user

- name: Install Dependencies
  ansible.builtin.shell: /home/ec2-user/github-runner/bin/installdependencies.sh

- name: Install Runner
  ansible.builtin.shell: ./config.sh remove --token {{secrets.GITHUB_RUNNER_TOKEN}}; ./config.sh --unattended --replace --url https://github.com/srikanth-123git --token {{secrets.GITHUB_RUNNER_TOKEN}}
  args:
    chdir: /home/ec2-user/github-runner
  become_user: ec2-user

- name: Start Runner
  ansible.builtin.shell: ./svc.sh install; ./svc.sh start
  args:
    chdir: /home/ec2-user/github-runner

- name: Disable default NodeJS Version Module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS module for V20
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Download Sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    dest: /opt
    remote_src: yes

