- name: Create Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/jobs/pipeline.xml') }}"
    name: test
    password: "{{secrets.jenkins_password}}"
    url: http://jenkins-internal.psrikanth.online:8080
    user: "{{secrets.jenkins_user}}"