- name: Install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.9

- name: Create Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/jobs/pipeline.xml') }}"
    name: "{{item}}"
    password: "{{secrets.jenkins_password}}"
    url: http://jenkins-internal.psrikanth.online:8080
    user: "{{secrets.jenkins_user}}"
  loop:
    - frontend
    - backend
