- name: Set Prompt
  ansible.builtin.shell: set-prompt jenkins

- name: Copy Jenkins repo file
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Java & Jenkins
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - fontconfig
      - jenkins
    state: installed

- name: Start Jenkins Service
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted
    enabled: yes

