- name: Jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins-setup.yml
  when: jenkins_setup | bool

- name: Jenkins Setup
  ansible.builtin.include_tasks:
    file: jenkins-jobs.yml
  when: jenkins_jobs | bool

