global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        port: 9090
        filters:
          - name: monitor
            values: ["yes", "true"]
