global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:monitor
            values: ["yes", "true"]

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
      - source_labels: [__meta_ec2_tag_env]
        target_label: env

  - job_name: "caddy"
    ec2_sd_configs:
      - region: us-east-1
        port: 2019
        filters:
          - name: tag:Name
            values: ["frontend-dev", "frontend-prod"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
      - source_labels: [__meta_ec2_tag_env]
        target_label: env